# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jv_ZbsTenkYC1anK45F0ThR4F9HYs2QC
"""

import streamlit as st

st.title('サプーアプリ')
st.caption('これはサプーの動画用のテストアプリです')

name = st.text_input('名前')
print(name)

submit_btn = st.button('送信')
cancel_btn = st.button('キャンセル')

if submit_btn:
    st.write('送信しました')
elif cancel_btn:
    st.write('キャンセルしました')

